from collections import defaultdict
from operator import length_hint
from typing import Dict, List, Tuple

from dzn.dzn_generation import SMSgreedy
from pandas.io.common import uses_relative


from sfs_generator.asm_block import AsmBlock
import sfs_generator.opcodes as opcodes
from smt_encoding import instructions
from split_stack_calculator.dag import DAG
import re


def is_hex(s):
    return len(s) == 2 and bool(re.fullmatch(r"[0-9a-fA-F]+", s))

'''
    Split calculator is responable of calculating the best position for splitting a block. 
    The split position can be calculated in two ways, in the places where the stack is of minimum size 
    or the place where the dag generated by the dependencies of the instructions can be splitted cutting the least amount of edges
'''
class Split_calculator:

    def get_minstack_split(self, source_stack_size: int, block_length:int, instrs: List[str], split_first: bool):


        stack_size = source_stack_size

        quart = block_length / 3
        lower_instr_num_bound = quart 
        upper_instr_num_bound = quart * 2

        min_stack_size = 1024
        min_instr_number = 0
        for instr_number, instr in enumerate(instrs):


            try:
                bytecode_info = opcodes.get_opcode(instr)
            except ValueError:
                continue
            stack_size = stack_size - bytecode_info[1] + bytecode_info[2]

            if split_first:
                store_stack = stack_size < min_stack_size
            else:
                store_stack = stack_size <= min_stack_size


            if (lower_instr_num_bound < instr_number < upper_instr_num_bound and store_stack):
                min_stack_size = stack_size 
                min_instr_number = instr_number

        return min_stack_size, min_instr_number


    def get_minstack_split_middle(self, source_stack_size: int, block_length:int, instrs: List[str], split_first: bool):


        stack_size = source_stack_size

        quart = block_length / 3
        lower_instr_num_bound = quart
        upper_instr_num_bound = quart * 2
        
        min_stack_size = 1024
        min_instr_number = 0
        min_stacks = []

        for instr_number, instr in enumerate(instrs):
            try:
                bytecode_info = opcodes.get_opcode(instr)
            except ValueError:
                continue
            stack_size = stack_size - bytecode_info[1] + bytecode_info[2]

            if not lower_instr_num_bound < instr_number < upper_instr_num_bound:
                continue


            if (stack_size < min_stack_size):
                min_stack_size = stack_size 
                min_stacks = [instr_number]

            elif stack_size == min_stack_size:
                min_stack_size = stack_size 
                min_stacks.append(instr_number)

        min_distance_from_center = len(instrs)
        for instr_number in min_stacks:
            dist = abs(len(instrs)/2 - instr_number) 
            
            if split_first:
                store_stack = dist < min_distance_from_center 
            else:
                store_stack = dist <= min_distance_from_center 

            if store_stack:
                min_distance_from_center = dist
                min_instr_number = instr_number


        return min_stack_size, min_instr_number


    def get_minstack_split_dag(self, dag, length:int, split_first:bool):

        id_to_pos = dag.id_to_pos

        quart = length/3
        min_pos_block = quart
        max_pos_block = quart * 2


        min_stack_size = 1024
        min_instr_number = 0


        for instr in dag.reverse:

            if split_first:
                store_stack = id_to_pos[instr][1] < min_stack_size
            else:
                store_stack = id_to_pos[instr][1] <= min_stack_size

            if (id_to_pos[instr][0] > min_pos_block and id_to_pos[instr][0] < max_pos_block and store_stack):
                min_instr_number = id_to_pos[instr][0]
                min_stack_size = id_to_pos[instr][1]

        return min_stack_size, min_instr_number

    def get_minstack_split_middle_dag(self, dag, length:int, split_first: bool):

        id_to_pos = dag.id_to_pos

        quart = length/3
        min_pos_block = quart
        max_pos_block = quart * 2


        min_stack_size = 1024
        min_instr_number = 0
        min_stacks = []


        for pos, instr in enumerate(dag.reverse):
            if not min_pos_block < id_to_pos[instr][0] < max_pos_block:
                continue

            if (id_to_pos[instr][1] < min_stack_size):
                min_stack_size = id_to_pos[instr][1] 
                min_stacks = [(pos, id_to_pos[instr][0])]


            elif id_to_pos[instr][1] == min_stack_size:
                min_stack_size = id_to_pos[instr][1] 
                min_stacks.append((pos, id_to_pos[instr][0]))

        min_distance_from_center = len(dag.reverse)
        for (dag_pos, instr_number) in min_stacks:
            dist = abs(len(dag.reverse)/2 - dag_pos) 
            
            if split_first:
                store_stack = dist < min_distance_from_center 
            else:
                store_stack = dist <= min_distance_from_center 

            if store_stack:
                min_distance_from_center = dist
                min_instr_number = instr_number

        return min_stack_size, min_instr_number


    def calculate_minstack_split(self, block:AsmBlock, split_first: bool, split_middle: bool):
        if split_middle:
            return self.get_minstack_split_middle(block.source_stack, block.length + 2, [instr.disasm for instr in block.instructions], split_first)
        else:
            return self.get_minstack_split(block.source_stack, block.length + 2, [instr.disasm for instr in block.instructions], split_first)



    def calculate_extended_dag_split(self, sfs_block: Dict, split_first: bool, split_middle:bool) -> None:


        original_code_with_ids, length = self.parse_original_instr(sfs_block["original_instrs"], sfs_block["user_instrs"], sfs_block["src_ws"], sfs_block["tgt_ws"])

        if length < 10:
            return

        if original_code_with_ids == []:
            print("no dag")
            if split_middle:
                min_stack_size, min_instr_number = self.get_minstack_split_middle(len(sfs_block["src_ws"]), sfs_block["init_progr_len"], [instr for instr in sfs_block["original_instrs"].split() if not is_hex(instr)], split_first)
            else:
                min_stack_size, min_instr_number = self.get_minstack_split(len(sfs_block["src_ws"]), sfs_block["init_progr_len"], [instr for instr in sfs_block["original_instrs"].split() if not is_hex(instr)], split_first)
            return min_stack_size, min_instr_number


        dag = DAG(sfs_block["instr_dependencies"], original_code_with_ids, length, extended=True)

        if split_middle:
            return self.get_minstack_split_middle_dag(dag, sfs_block["init_progr_len"] + 2, split_first)
        else:
            return self.get_minstack_split_dag(dag, sfs_block["init_progr_len"] + 2, split_first)

        

        #dag.render_graph(min_stack_size, min_instr_number, sfs_block["user_instrs"])

        _, first_minstack = self.get_minstack_split(len(sfs_block["src_ws"]), sfs_block["init_progr_len"], [instr for instr in sfs_block["original_instrs"].split() if not is_hex(instr)], True)

        _, last_minstack = self.get_minstack_split(len(sfs_block["src_ws"]), sfs_block["init_progr_len"], [instr for instr in sfs_block["original_instrs"].split() if not is_hex(instr)], False)

        return min_stack_size, min_instr_number

    def parse_original_instr(self, original_instr: str, user_instr: List[Dict], stack: List[str], final_stack: List[str], code_with_ids_and_pos_size=[], pos=0) -> Tuple[List[Tuple[str, int, int]], int]:


        original_instr_splitted = original_instr.split(" ")
        stack = stack.copy()

        user_instr_dict = defaultdict(list)

        for instr in user_instr:
            user_instr_dict[instr["disasm"]].append(instr)

        for i, word in enumerate(original_instr_splitted):
            if i > 0 and original_instr_splitted[i-1].startswith("PUSH") or word[0].isdigit():
                continue



            if word.startswith("PUSH0"):
                if "PUSH0" in user_instr_dict.keys():
                    push0 = user_instr_dict["PUSH0"][0]
                    code_with_ids_and_pos_size.append((push0["id"], pos, len(stack)))
                    stack = push0["outpt_sk"] + stack
                else:
                    stack = ["none"] + stack

            elif word.startswith("PUSH") and "[" in original_instr_splitted[i + 1]: # [tag] or any of its derivated values ([$], #[$]...)
                value = int(original_instr_splitted[i + 2], 10)
                for push in user_instr_dict[f"PUSH {original_instr_splitted[i + 1]}"]:
                    if push["value"][0] == value:
                        code_with_ids_and_pos_size.append((push["id"], pos, len(stack)))
                        stack = push["outpt_sk"] + stack

            elif word.startswith("PUSH") and "data" in original_instr_splitted[i + 1]: # [tag] or any of its derivated values ([$], #[$]...)
                value = int(original_instr_splitted[i + 2], 16)
                for push in user_instr_dict[f"PUSH {original_instr_splitted[i + 1]}"]:
                    if push["value"][0] == value:
                        code_with_ids_and_pos_size.append((push["id"], pos, len(stack)))
                        stack = push["outpt_sk"] + stack

            elif word.startswith("PUSH") and len(word) < 8:
                value = int(original_instr_splitted[i + 1], 16)

                if "PUSH" not in user_instr_dict.keys():
                    return [], 0
                
                for push in user_instr_dict["PUSH"]:
                    if push["value"][0] == value:
                        code_with_ids_and_pos_size.append((push["id"], pos, len(stack)))
                        stack = push["outpt_sk"] + stack


            elif word.startswith("KECCAK256"):
                for kw in user_instr_dict[word]:
                    kw_input = kw["inpt_sk"] 
                    st_input = stack[:len(kw["inpt_sk"])]
                    if kw_input == st_input:

                        original_pos = pos
                        original_code_with_ids_and_pos_size = code_with_ids_and_pos_size.copy()
                        original_stack = stack.copy()


                        code_with_ids_and_pos_size.append((kw["id"], pos, len(stack)))
                        stack = stack[len(kw["inpt_sk"]):]
                        stack = kw["outpt_sk"] + stack


                        backtracking, pos = self.parse_original_instr(original_instr[len(" ".join(original_instr_splitted[0:i + 1])) + 1:],user_instr, stack, final_stack, code_with_ids_and_pos_size, pos)


                        if len(backtracking) != 0:
                            return backtracking, pos

                        stack = original_stack
                        pos = original_pos
                        code_with_ids_and_pos_size = original_code_with_ids_and_pos_size


            elif word.startswith("MLOAD"):
                for kw in user_instr_dict[word]:
                    kw_input = kw["inpt_sk"] 
                    st_input = stack[:len(kw["inpt_sk"])]
                    if kw_input == st_input:

                        original_pos = pos
                        original_code_with_ids_and_pos_size = code_with_ids_and_pos_size.copy()
                        original_stack = stack.copy()


                        code_with_ids_and_pos_size.append((kw["id"], pos, len(stack)))
                        stack = stack[len(kw["inpt_sk"]):]
                        stack = kw["outpt_sk"] + stack


                        backtracking, pos = self.parse_original_instr(original_instr[len(" ".join(original_instr_splitted[0:i + 1])) + 1:],user_instr, stack, final_stack, code_with_ids_and_pos_size, pos + 1)


                        if len(backtracking) != 0:
                            return backtracking, pos

                        stack = original_stack
                        pos = original_pos
                        code_with_ids_and_pos_size = original_code_with_ids_and_pos_size


            elif word.startswith("SWAP"):
                value = int(word.replace("SWAP", ""))
                stack[0], stack[value] = stack[value], stack[0]

            elif word.startswith("DUP"):
                value = int(word.replace("DUP", ""))-1
                stack = [stack[value]] + stack

            elif word.startswith("POP"):
                stack = stack[1:]


            else:
                temp_stack = stack.copy()
                for kw in user_instr_dict[word]:
                    if kw["commutative"]:
                        kw_input = set(kw["inpt_sk"])
                        st_input = set(stack[:len(kw["inpt_sk"])])
                    else:
                        kw_input = kw["inpt_sk"] 
                        st_input = stack[:len(kw["inpt_sk"])]

                    if kw_input == st_input:
                        code_with_ids_and_pos_size.append((kw["id"], pos, len(temp_stack)))
                        temp_stack = temp_stack[len(kw["inpt_sk"]):]
                        temp_stack = kw["outpt_sk"] + temp_stack

                stack = temp_stack

            pos += 1
        
        if stack == final_stack:
            return code_with_ids_and_pos_size, pos
        else:
            return [], pos

